
/**
 * This code was generated by "react-native codegen-harmony"
 *
 * Do not edit this file as changes may cause incorrect behavior and will be
 * lost once the code is regenerated.
 *
 * @generatorVersion: 1
 */
#include "RNDatePicker.h"

namespace rnoh {
using namespace facebook;

RNDatePicker::RNDatePicker(const ArkTSTurboModule::Context ctx, const std::string name) : ArkTSTurboModule(ctx, name) {
    methodMap_ = {
        ARK_METHOD_METADATA(getConstants, 0),
        ARK_METHOD_METADATA(closePicker, 0),
        ARK_METHOD_METADATA(openPicker, 1),
        ARK_METHOD_METADATA(removeListeners, 1),
        ARK_METHOD_METADATA(addListener, 1),
    };
}

} // namespace rnoh
