#pragma once

/**
 * This code was generated by "react-native codegen-harmony"
 *
 * Do not edit this file as changes may cause incorrect behavior and will be
 * lost once the code is regenerated.
 *
 * @generatorVersion: 1
 */

#include "RNOHCorePackage/ComponentBinders/ViewComponentJSIBinder.h"

namespace rnoh {
class RNDatePickerJSIBinder : public ViewComponentJSIBinder {
  protected:
    facebook::jsi::Object createNativeProps(facebook::jsi::Runtime &rt) override {
        auto object = ViewComponentJSIBinder::createNativeProps(rt);
        object.setProperty(rt, "locale", true);
        object.setProperty(rt, "date", true);
        object.setProperty(rt, "maximumDate", true);
        object.setProperty(rt, "minimumDate", true);
        object.setProperty(rt, "minuteInterval", true);
        object.setProperty(rt, "mode", true);
        object.setProperty(rt, "timeZoneOffsetInMinutes", true);
        object.setProperty(rt, "textColor", true);
        object.setProperty(rt, "dividerColor", true);
        object.setProperty(rt, "buttonColor", true);
        object.setProperty(rt, "is24hourSource", true);
        object.setProperty(rt, "theme", true);
        object.setProperty(rt, "modal", true);
        object.setProperty(rt, "open", true);
        object.setProperty(rt, "confirmText", true);
        object.setProperty(rt, "cancelText", true);
        object.setProperty(rt, "title", true);
        return object;
    }

    facebook::jsi::Object createBubblingEventTypes(facebook::jsi::Runtime &rt) override {
        facebook::jsi::Object events(rt);
        events.setProperty(rt, "topChange", createBubblingCapturedEvent(rt, "onChange"));
        events.setProperty(rt, "topConfirm", createBubblingCapturedEvent(rt, "onConfirm"));
        events.setProperty(rt, "topCancel", createBubblingCapturedEvent(rt, "onCancel"));
        return events;
    }

    facebook::jsi::Object createDirectEventTypes(facebook::jsi::Runtime &rt) override {
        facebook::jsi::Object events(rt);
        return events;
    }
};
} // namespace rnoh
