
/**
 * This code was generated by "react-native codegen-harmony"
 *
 * Do not edit this file as changes may cause incorrect behavior and will be
 * lost once the code is regenerated.
 *
 * @generatorVersion: 1
 */
#pragma once

#include <react/renderer/core/ConcreteComponentDescriptor.h>
#include <react/renderer/components/view/ConcreteViewShadowNode.h>
#include <react/renderer/components/view/ViewShadowNode.h>

namespace facebook {
namespace react {

extern const char RNDatePickerComponentName[] = "RNDatePicker";

class RNDatePickerProps : public ViewProps {
  public:
    RNDatePickerProps() = default;

    RNDatePickerProps(const PropsParserContext &context, const RNDatePickerProps &sourceProps, const RawProps &rawProps)
        : ViewProps(context, sourceProps, rawProps) {}
};

using RNDatePickerShadowNode = ConcreteViewShadowNode<
    RNDatePickerComponentName,
    RNDatePickerProps,
    ViewEventEmitter>;

class RNDatePickerComponentDescriptor final
    : public ConcreteComponentDescriptor<RNDatePickerShadowNode> {
  public:
    RNDatePickerComponentDescriptor(ComponentDescriptorParameters const &parameters)
        : ConcreteComponentDescriptor(parameters) {}
};

} // namespace react
} // namespace facebook
