/**
 * This code was generated by "react-native codegen-harmony"
 *
 * Do not edit this file as changes may cause incorrect behavior and will be
 * lost once the code is regenerated.
 *
 * @generatorVersion: 1
 */

import { Tag } from "@rnoh/react-native-openharmony/ts"

export namespace RNDatePicker {
  export const NAME = 'RNDatePicker' as const

  export interface Spec {
    getConstants(): {};
  
    closePicker(): void;
  
    openPicker(props: Object): void;
  
    removeListeners(type: number): void;
  
    addListener(eventName: string): void;
  
  }
}
